language: python
dist: focal  
python:
  - "3.10"   

before_install:
  - sudo apt-get update

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot python-telegram-bot pymongo pyTelegramBotAPI certifi pytz

script:
  - chmod +x bgmi && chmod +x bgmi1 && chmod +x bgmi2 && python3 main.py
